# Vendor Performance Analytics ETL Pipeline

## ETL Pipeline Overview

This notebook focuses on building a structured ETL (Extract, Transform, Load) pipeline for vendor, sales, inventory, and procurement analytics. The pipeline prepares cleaned, transformed, and dashboard-ready datasets for advanced business intelligence workflows, SQL analytics, and Power BI reporting.

---

# ETL Objectives

- Extract raw business datasets
- Perform data cleaning & validation
- Handle missing and duplicate records
- Transform datatypes and business fields
- Engineer analytical KPI features
- Create dashboard-ready datasets
- Prepare SQL & Power BI compatible outputs

---

# Technologies Used

- Python
- Pandas
- NumPy
- Google Colab
- CSV Processing
- SQL-ready Transformations
- Power BI-ready Data Exports

# ETL Workflow

1. Data Extraction
2. Data Validation
3. Missing Value Handling
4. Duplicate Validation
5. Datatype Transformation
6. Feature Engineering
7. Business KPI Engineering
8. Aggregation Pipelines
9. Export Pipelines
10. Dashboard-ready Dataset Generation

In [ ]:
import pandas as pd
import numpy as np

# Data Extraction

In [ ]:
sales = pd.read_csv('/content/sales.csv')

purchases = pd.read_csv('/content/purchases.csv')

begin_inventory = pd.read_csv('/content/begin_inventory.csv')

end_inventory = pd.read_csv('/content/end_inventory.csv')

purchase_prices = pd.read_csv('/content/purchase_prices.csv')

vendor_invoice = pd.read_csv('/content/vendor_invoice.csv')

print("All datasets extracted successfully ✅")

All datasets extracted successfully ✅

# Dataset Validation

In [ ]:
datasets = {
    "sales": sales,
    "purchases": purchases,
    "begin_inventory": begin_inventory,
    "end_inventory": end_inventory,
    "purchase_prices": purchase_prices,
    "vendor_invoice": vendor_invoice
}

for name, df in datasets.items():

    print("\n", "="*50)
    print(f"Dataset: {name.upper()}")
    print("="*50)

    print("Rows:", df.shape[0])
    print("Columns:", df.shape[1])

 ==================================================
Dataset: SALES
==================================================
Rows: 33719
Columns: 14

 ==================================================
Dataset: PURCHASES
==================================================
Rows: 34589
Columns: 16

 ==================================================
Dataset: BEGIN_INVENTORY
==================================================
Rows: 75593
Columns: 9

 ==================================================
Dataset: END_INVENTORY
==================================================
Rows: 62913
Columns: 9

 ==================================================
Dataset: PURCHASE_PRICES
==================================================
Rows: 12261
Columns: 9

 ==================================================
Dataset: VENDOR_INVOICE
==================================================
Rows: 5543
Columns: 10

## Validation Observation

The extracted datasets contain large-scale operational business records suitable for enterprise-level ETL workflows, KPI engineering, dashboard analytics, and business intelligence reporting.

# Missing Value Validation

In [ ]:
for name, df in datasets.items():

    print("\n", "="*50)
    print(f"Missing Values in {name.upper()}")
    print("="*50)

    print(df.isnull().sum())

 ==================================================
Missing Values in SALES
==================================================
InventoryId       0
Store             0
Brand             0
Description       0
Size              1
SalesQuantity     1
SalesDollars      1
SalesPrice        1
SalesDate         1
Volume            1
Classification    1
ExciseTax         1
VendorNo          1
VendorName        1
dtype: int64

 ==================================================
Missing Values in PURCHASES
==================================================
InventoryId       0
Store             0
Brand             0
Description       0
Size              1
VendorNumber      1
VendorName        1
PONumber          1
PODate            1
ReceivingDate     1
InvoiceDate       1
PayDate           1
PurchasePrice     1
Quantity          1
Dollars           1
Classification    1
dtype: int64

 ==================================================
Missing Values in BEGIN_INVENTORY
==================================================
InventoryId    0
Store          1
City           1
Brand          1
Description    1
Size           1
onHand         1
Price          1
startDate      1
dtype: int64

 ==================================================
Missing Values in END_INVENTORY
==================================================
InventoryId    0
Store          0
City           0
Brand          0
Description    0
Size           1
onHand         1
Price          1
endDate        1
dtype: int64

 ==================================================
Missing Values in PURCHASE_PRICES
==================================================
Brand             0
Description       1
Price             0
Size              1
Volume            1
Classification    0
PurchasePrice     0
VendorNumber      0
VendorName        0
dtype: int64

 ==================================================
Missing Values in VENDOR_INVOICE
==================================================
VendorNumber       0
VendorName         0
InvoiceDate        0
PONumber           0
PODate             0
PayDate            0
Quantity           0
Dollars            0
Freight            0
Approval        5169
dtype: int64

## ETL Observation

The datasets contain minimal missing values. Missing records mainly appear in vendor approval and location-related fields, representing minor operational inconsistencies in business transactions.

# Duplicate Record Validation

In [ ]:
for name, df in datasets.items():

    print("\n", "="*50)
    print(f"Duplicate Records in {name.upper()}")
    print("="*50)

    print("Duplicate Rows:", df.duplicated().sum())

 ==================================================
Duplicate Records in SALES
==================================================
Duplicate Rows: 0

 ==================================================
Duplicate Records in PURCHASES
==================================================
Duplicate Rows: 0

 ==================================================
Duplicate Records in BEGIN_INVENTORY
==================================================
Duplicate Rows: 0

 ==================================================
Duplicate Records in END_INVENTORY
==================================================
Duplicate Rows: 0

 ==================================================
Duplicate Records in PURCHASE_PRICES
==================================================
Duplicate Rows: 0

 ==================================================
Duplicate Records in VENDOR_INVOICE
==================================================
Duplicate Rows: 0

## ETL Observation

Duplicate validation ensures transactional consistency and prevents inflated KPI calculations, duplicate revenue generation, and inventory inaccuracies during analytical processing.

# Datatype Standardization

In [ ]:
sales['SalesDate'] = pd.to_datetime(
    sales['SalesDate']
)

purchases['PODate'] = pd.to_datetime(
    purchases['PODate']
)

vendor_invoice['InvoiceDate'] = pd.to_datetime(
    vendor_invoice['InvoiceDate']
)

print("Date columns standardized successfully ✅")

Date columns standardized successfully ✅

In [ ]:
sales.info()

purchases.info()

vendor_invoice.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33719 entries, 0 to 33718
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   InventoryId     33719 non-null  object
 1   Store           33719 non-null  int64
 2   Brand           33719 non-null  int64
 3   Description     33719 non-null  object
 4   Size            33718 non-null  object
 5   SalesQuantity   33718 non-null  float64
 6   SalesDollars    33718 non-null  float64
 7   SalesPrice      33718 non-null  float64
 8   SalesDate       33718 non-null  datetime64[ns]
 9   Volume          33718 non-null  float64
 10  Classification  33718 non-null  float64
 11  ExciseTax       33718 non-null  float64
 12  VendorNo        33718 non-null  float64
 13  VendorName      33718 non-null  object
dtypes: datetime64[ns](1), float64(7), int64(2), object(4)
memory usage: 3.6+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34589 entries, 0 to 34588
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   InventoryId     34589 non-null  object
 1   Store           34589 non-null  int64
 2   Brand           34589 non-null  int64
 3   Description     34589 non-null  object
 4   Size            34588 non-null  object
 5   VendorNumber    34588 non-null  float64
 6   VendorName      34588 non-null  object
 7   PONumber        34588 non-null  float64
 8   PODate          34588 non-null  datetime64[ns]
 9   ReceivingDate   34588 non-null  object
 10  InvoiceDate     34588 non-null  object
 11  PayDate         34588 non-null  object
 12  PurchasePrice   34588 non-null  float64
 13  Quantity        34588 non-null  float64
 14  Dollars         34588 non-null  float64
 15  Classification  34588 non-null  float64
dtypes: datetime64[ns](1), float64(6), int64(2), object(7)
memory usage: 4.2+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5543 entries, 0 to 5542
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   VendorNumber  5543 non-null   int64
 1   VendorName    5543 non-null   object
 2   InvoiceDate   5543 non-null   datetime64[ns]
 3   PONumber      5543 non-null   int64
 4   PODate        5543 non-null   object
 5   PayDate       5543 non-null   object
 6   Quantity      5543 non-null   int64
 7   Dollars       5543 non-null   float64
 8   Freight       5543 non-null   float64
 9   Approval      374 non-null    object
dtypes: datetime64[ns](1), float64(2), int64(3), object(4)
memory usage: 433.2+ KB

## Transformation Observation

Date standardization enables time-series analysis, monthly KPI generation, forecasting preparation, and dashboard compatibility for business intelligence workflows.

# Missing Value Handling

In [ ]:
sales = sales.dropna().copy()

purchases = purchases.dropna().copy()

begin_inventory = begin_inventory.dropna().copy()

end_inventory = end_inventory.dropna().copy()

In [ ]:
print("Sales Null Values:",
      sales.isnull().sum().sum())

print("Purchases Null Values:",
      purchases.isnull().sum().sum())

print("Begin Inventory Null Values:",
      begin_inventory.isnull().sum().sum())

print("End Inventory Null Values:",
      end_inventory.isnull().sum().sum())

Sales Null Values: 0
Purchases Null Values: 0
Begin Inventory Null Values: 0
End Inventory Null Values: 0

## Cleaning Observation

The datasets were permanently cleaned to remove incomplete operational records and improve analytical consistency for downstream dashboarding and KPI workflows.

# Feature Engineering

In [ ]:
sales['Revenue_Per_Unit'] = (
    sales['SalesDollars']
    / sales['SalesQuantity']
)

sales['Year'] = sales['SalesDate'].dt.year

sales['Month'] = sales['SalesDate'].dt.month

sales['Month_Name'] = sales['SalesDate'].dt.month_name()

sales['Day'] = sales['SalesDate'].dt.day

In [ ]:
begin_inventory['InventoryValue'] = (
    begin_inventory['onHand']
    * begin_inventory['Price']
)

end_inventory['InventoryValue'] = (
    end_inventory['onHand']
    * end_inventory['Price']
)

## Feature Engineering Observation

Additional KPI and analytical fields were generated to support inventory valuation, time-series analysis, profitability analytics, and dashboard-ready business intelligence reporting.

# Aggregation Pipelines

## Vendor Revenue Summary Table

In [ ]:
vendor_summary = sales.groupby(
    'VendorName'
).agg({

    'SalesDollars':'sum',
    'SalesQuantity':'sum',
    'Revenue_Per_Unit':'mean'

}).reset_index()

In [ ]:
vendor_summary.rename(columns={

    'SalesDollars':'Total_Revenue',
    'SalesQuantity':'Total_Quantity_Sold',
    'Revenue_Per_Unit':'Average_Revenue_Per_Unit'

}, inplace=True)

In [ ]:
vendor_summary.head()

,VendorName,Total_Revenue,Total_Quantity_Sold,Average_Revenue_Per_Unit
0,ALTAMAR BRANDS LLC,84.94,6.0,14.156667
1,AMERICAN VINTAGE BEVERAGE,402.69,31.0,12.990000
2,ATLANTIC IMPORTING COMPANY,258.93,7.0,36.990000
3,BACARDI USA INC,60952.39,3961.0,16.751149
4,BANFI PRODUCTS CORP,9078.69,831.0,11.231848

## Aggregation Observation

The vendor summary table provides vendor-level KPI metrics suitable for dashboard reporting, vendor ranking, profitability analysis, and procurement intelligence workflows.

## Product Performance Summary Table

In [ ]:
product_summary = sales.groupby(
    'Description'
).agg({

    'SalesDollars':'sum',
    'SalesQuantity':'sum',
    'Revenue_Per_Unit':'mean'

}).reset_index()

In [ ]:
product_summary.rename(columns={

    'SalesDollars':'Total_Product_Revenue',
    'SalesQuantity':'Total_Product_Quantity',
    'Revenue_Per_Unit':'Average_Revenue_Per_Unit'

}, inplace=True)

In [ ]:
product_summary.head()

,Description,Total_Product_Revenue,Total_Product_Quantity,Average_Revenue_Per_Unit
0,(RI) 1,36.99,1.0,36.990000
1,14 Hands Cab Svgn Wash,854.16,72.0,11.725652
2,14 Hands Chard Wash,77.85,7.0,10.774000
3,14 Hands Hot to Trot Red,439.60,40.0,10.990000
4,14 Hands Merlot Wash,263.61,23.0,11.483333

## Store Performance Summary Table

In [ ]:
store_summary = sales.groupby(
    'Store'
).agg({

    'SalesDollars':'sum',
    'SalesQuantity':'sum'

}).reset_index()

In [ ]:
store_summary.rename(columns={

    'SalesDollars':'Total_Store_Revenue',
    'SalesQuantity':'Total_Store_Quantity'

}, inplace=True)

In [ ]:
store_summary.head()

   Store  Total_Store_Revenue  Total_Store_Quantity
0      1            496657.18               42052.0
1     10            532695.09               41911.0

## Inventory Summary Table

In [ ]:
inventory_summary = end_inventory.groupby(
    'Description'
).agg({

    'onHand':'sum',
    'InventoryValue':'sum'

}).reset_index()

In [ ]:
inventory_summary.rename(columns={

    'onHand':'Remaining_Stock',
    'InventoryValue':'Remaining_Inventory_Value'

}, inplace=True)

In [ ]:
inventory_summary.head()

              Description  Remaining_Stock  Remaining_Inventory_Value
0                  (RI) 1             61.0                    2134.39
1     10 Span Cab Svgn CC              5.0                      37.45
2      1000 Stories Znfdl              1.0                      15.99
3      13 Celsius Svgn Bl             89.0                     978.11
4  14 Hands Cab Svgn Wash            963.0                    8657.37

## ETL Aggregation Observation

Aggregated analytical tables significantly reduce dashboard processing complexity and improve Power BI performance by transforming raw transactional records into summarized KPI-ready datasets.

# Export Pipelines

## Cleaned Sales Dataset Export

In [ ]:
sales.to_csv(
    'cleaned_sales.csv',
    index=False
)

print("Cleaned sales dataset exported successfully ✅")

Cleaned sales dataset exported successfully ✅

## Vendor Summary Export

In [ ]:
vendor_summary.to_csv(
    'vendor_summary.csv',
    index=False
)

print("Vendor summary exported successfully ✅")

Vendor summary exported successfully ✅

## Product Summary Export

In [ ]:
product_summary.to_csv(
    'product_summary.csv',
    index=False
)

print("Product summary exported successfully ✅")

Product summary exported successfully ✅

## Store Summary Export

In [ ]:
store_summary.to_csv(
    'store_summary.csv',
    index=False
)

print("Store summary exported successfully ✅")

Store summary exported successfully ✅

## Inventory Summary Export

In [ ]:
inventory_summary.to_csv(
    'inventory_summary.csv',
    index=False
)

print("Inventory summary exported successfully ✅")

Inventory summary exported successfully ✅

# Export Validation

In [ ]:
import os

exported_files = [

    'cleaned_sales.csv',
    'vendor_summary.csv',
    'product_summary.csv',
    'store_summary.csv',
    'inventory_summary.csv'
]

for file in exported_files:

    print(file, "→", os.path.exists(file))

cleaned_sales.csv → True
vendor_summary.csv → True
product_summary.csv → True
store_summary.csv → True
inventory_summary.csv → True

## ETL Export Observation

The transformed analytical datasets were successfully exported into dashboard-ready CSV files suitable for Power BI integration, SQL workflows, business intelligence reporting, and downstream analytical systems.

# Power BI Integration Preparation

The exported summary datasets are optimized for:
- KPI dashboards
- Vendor analytics
- Inventory monitoring
- Store performance dashboards
- Procurement intelligence
- Profitability analysis

The aggregated datasets significantly reduce dashboard load complexity and improve visualization performance compared to raw transactional data.

# SQL Integration Preparation

The ETL pipeline generates structured analytical tables suitable for:
- SQL querying
- KPI reporting
- aggregation analysis
- dashboard integration
- business intelligence workflows

The exported datasets can be directly imported into MySQL, PostgreSQL, or SQL Server environments for advanced analytical operations.

# ETL Pipeline Conclusion

This ETL pipeline successfully extracted, cleaned, transformed, validated, aggregated, and exported enterprise-scale business datasets into structured analytical outputs. The workflow demonstrates professional ETL engineering practices including data quality validation, feature engineering, aggregation pipelines, KPI-ready transformations, and dashboard-ready dataset generation suitable for real-world business intelligence systems.